// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: mission_generator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateMissionRequest_MissionFormat int32

const (
	GenerateMissionRequest_COMBAT_PATROL GenerateMissionRequest_MissionFormat = 0
	GenerateMissionRequest_INCURSION     GenerateMissionRequest_MissionFormat = 1
)

// Enum value maps for GenerateMissionRequest_MissionFormat.
var (
	GenerateMissionRequest_MissionFormat_name = map[int32]string{
		0: "COMBAT_PATROL",
		1: "INCURSION",
	}
	GenerateMissionRequest_MissionFormat_value = map[string]int32{
		"COMBAT_PATROL": 0,
		"INCURSION":     1,
	}
)

func (x GenerateMissionRequest_MissionFormat) Enum() *GenerateMissionRequest_MissionFormat {
	p := new(GenerateMissionRequest_MissionFormat)
	*p = x
	return p
}

func (x GenerateMissionRequest_MissionFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateMissionRequest_MissionFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_mission_generator_proto_enumTypes[0].Descriptor()
}

func (GenerateMissionRequest_MissionFormat) Type() protoreflect.EnumType {
	return &file_mission_generator_proto_enumTypes[0]
}

func (x GenerateMissionRequest_MissionFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateMissionRequest_MissionFormat.Descriptor instead.
func (GenerateMissionRequest_MissionFormat) EnumDescriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{0, 0}
}

type GenerateMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionFormat GenerateMissionRequest_MissionFormat `protobuf:"varint,1,opt,name=missionFormat,proto3,enum=mGenerator.GenerateMissionRequest_MissionFormat" json:"missionFormat,omitempty"`
}

func (x *GenerateMissionRequest) Reset() {
	*x = GenerateMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMissionRequest) ProtoMessage() {}

func (x *GenerateMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMissionRequest.ProtoReflect.Descriptor instead.
func (*GenerateMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateMissionRequest) GetMissionFormat() GenerateMissionRequest_MissionFormat {
	if x != nil {
		return x.MissionFormat
	}
	return GenerateMissionRequest_COMBAT_PATROL
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Links []*Point `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetLinks() []*Point {
	if x != nil {
		return x.Links
	}
	return nil
}

type Mission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules       string               `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	Twist       *Mission_Twist       `protobuf:"bytes,4,opt,name=twist,proto3" json:"twist,omitempty"`
	Deployment  *Mission_Deployment  `protobuf:"bytes,5,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Battlefield *Mission_Battlefield `protobuf:"bytes,6,opt,name=battlefield,proto3" json:"battlefield,omitempty"`
	Objectives  []*Mission_Objective `protobuf:"bytes,7,rep,name=objectives,proto3" json:"objectives,omitempty"`
	Terrain     []*Mission_Terrain   `protobuf:"bytes,8,rep,name=terrain,proto3" json:"terrain,omitempty"`
}

func (x *Mission) Reset() {
	*x = Mission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2}
}

func (x *Mission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Mission) GetTwist() *Mission_Twist {
	if x != nil {
		return x.Twist
	}
	return nil
}

func (x *Mission) GetDeployment() *Mission_Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *Mission) GetBattlefield() *Mission_Battlefield {
	if x != nil {
		return x.Battlefield
	}
	return nil
}

func (x *Mission) GetObjectives() []*Mission_Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *Mission) GetTerrain() []*Mission_Terrain {
	if x != nil {
		return x.Terrain
	}
	return nil
}

type Mission_Twist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules       string `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
}

func (x *Mission_Twist) Reset() {
	*x = Mission_Twist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Twist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Twist) ProtoMessage() {}

func (x *Mission_Twist) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Twist.ProtoReflect.Descriptor instead.
func (*Mission_Twist) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Mission_Twist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Twist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission_Twist) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type Mission_Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerAPoints  []*Point `protobuf:"bytes,1,rep,name=player_a_points,json=playerAPoints,proto3" json:"player_a_points,omitempty"`
	PlayerBPoints  []*Point `protobuf:"bytes,2,rep,name=player_b_points,json=playerBPoints,proto3" json:"player_b_points,omitempty"`
	DistancePoints []*Point `protobuf:"bytes,3,rep,name=distance_points,json=distancePoints,proto3" json:"distance_points,omitempty"`
}

func (x *Mission_Deployment) Reset() {
	*x = Mission_Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Deployment) ProtoMessage() {}

func (x *Mission_Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Deployment.ProtoReflect.Descriptor instead.
func (*Mission_Deployment) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Mission_Deployment) GetPlayerAPoints() []*Point {
	if x != nil {
		return x.PlayerAPoints
	}
	return nil
}

func (x *Mission_Deployment) GetPlayerBPoints() []*Point {
	if x != nil {
		return x.PlayerBPoints
	}
	return nil
}

func (x *Mission_Deployment) GetDistancePoints() []*Point {
	if x != nil {
		return x.DistancePoints
	}
	return nil
}

type Mission_Battlefield struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Width      int32  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height     int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	PowerLevel int32  `protobuf:"varint,4,opt,name=power_level,json=powerLevel,proto3" json:"power_level,omitempty"`
	Points     int32  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *Mission_Battlefield) Reset() {
	*x = Mission_Battlefield{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Battlefield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Battlefield) ProtoMessage() {}

func (x *Mission_Battlefield) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Battlefield.ProtoReflect.Descriptor instead.
func (*Mission_Battlefield) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Mission_Battlefield) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Battlefield) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Mission_Battlefield) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Mission_Battlefield) GetPowerLevel() int32 {
	if x != nil {
		return x.PowerLevel
	}
	return 0
}

func (x *Mission_Battlefield) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type Mission_Objective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RulesText       string   `protobuf:"bytes,3,opt,name=rules_text,json=rulesText,proto3" json:"rules_text,omitempty"`
	Primary         bool     `protobuf:"varint,4,opt,name=primary,proto3" json:"primary,omitempty"`
	ObjectivePoints []*Point `protobuf:"bytes,5,rep,name=objective_points,json=objectivePoints,proto3" json:"objective_points,omitempty"`
}

func (x *Mission_Objective) Reset() {
	*x = Mission_Objective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Objective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Objective) ProtoMessage() {}

func (x *Mission_Objective) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Objective.ProtoReflect.Descriptor instead.
func (*Mission_Objective) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Mission_Objective) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Objective) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission_Objective) GetRulesText() string {
	if x != nil {
		return x.RulesText
	}
	return ""
}

func (x *Mission_Objective) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *Mission_Objective) GetObjectivePoints() []*Point {
	if x != nil {
		return x.ObjectivePoints
	}
	return nil
}

type Mission_Terrain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Category    *Mission_Terrain_Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rules       string                    `protobuf:"bytes,4,opt,name=rules,proto3" json:"rules,omitempty"`
	RulesShort  string                    `protobuf:"bytes,5,opt,name=rules_short,json=rulesShort,proto3" json:"rules_short,omitempty"`
	Traits      []*Mission_Terrain_Trait  `protobuf:"bytes,6,rep,name=traits,proto3" json:"traits,omitempty"`
	Point       *Point                    `protobuf:"bytes,7,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *Mission_Terrain) Reset() {
	*x = Mission_Terrain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Terrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Terrain) ProtoMessage() {}

func (x *Mission_Terrain) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Terrain.ProtoReflect.Descriptor instead.
func (*Mission_Terrain) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Mission_Terrain) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Terrain) GetCategory() *Mission_Terrain_Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Mission_Terrain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission_Terrain) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Mission_Terrain) GetRulesShort() string {
	if x != nil {
		return x.RulesShort
	}
	return ""
}

func (x *Mission_Terrain) GetTraits() []*Mission_Terrain_Trait {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *Mission_Terrain) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type Mission_Terrain_Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Rules      string `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	RulesShort string `protobuf:"bytes,3,opt,name=rules_short,json=rulesShort,proto3" json:"rules_short,omitempty"`
}

func (x *Mission_Terrain_Category) Reset() {
	*x = Mission_Terrain_Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Terrain_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Terrain_Category) ProtoMessage() {}

func (x *Mission_Terrain_Category) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Terrain_Category.ProtoReflect.Descriptor instead.
func (*Mission_Terrain_Category) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 4, 0}
}

func (x *Mission_Terrain_Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Terrain_Category) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Mission_Terrain_Category) GetRulesShort() string {
	if x != nil {
		return x.RulesShort
	}
	return ""
}

type Mission_Terrain_Trait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Rules      string `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	RulesShort string `protobuf:"bytes,3,opt,name=rules_short,json=rulesShort,proto3" json:"rules_short,omitempty"`
}

func (x *Mission_Terrain_Trait) Reset() {
	*x = Mission_Terrain_Trait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Terrain_Trait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Terrain_Trait) ProtoMessage() {}

func (x *Mission_Terrain_Trait) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Terrain_Trait.ProtoReflect.Descriptor instead.
func (*Mission_Terrain_Trait) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2, 4, 1}
}

func (x *Mission_Terrain_Trait) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Terrain_Trait) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Mission_Terrain_Trait) GetRulesShort() string {
	if x != nil {
		return x.RulesShort
	}
	return ""
}

var File_mission_generator_proto protoreflect.FileDescriptor

var file_mission_generator_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x56, 0x0a, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x31, 0x0a, 0x0d, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x4d,
	0x42, 0x41, 0x54, 0x5f, 0x50, 0x41, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x49, 0x4e, 0x43, 0x55, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x22, 0x4c, 0x0a, 0x05, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x12, 0x27, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0xb3, 0x0b, 0x0a, 0x07, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x74, 0x77, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x77, 0x69, 0x73, 0x74, 0x52, 0x05, 0x74,
	0x77, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x0b, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69,
	0x6e, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x07, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x55, 0x0a,
	0x05, 0x54, 0x77, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x1a, 0xbe, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x61, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x39,
	0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x42, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0f, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x8a, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x1a, 0xba, 0x01, 0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x3c, 0x0a, 0x10, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0f,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a,
	0xcd, 0x03, 0x0a, 0x07, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x40, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x06,
	0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x74, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x1a, 0x57, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x1a, 0x54, 0x0a, 0x05, 0x54, 0x72, 0x61,
	0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x32,
	0x57, 0x0a, 0x10, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x22, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mission_generator_proto_rawDescOnce sync.Once
	file_mission_generator_proto_rawDescData = file_mission_generator_proto_rawDesc
)

func file_mission_generator_proto_rawDescGZIP() []byte {
	file_mission_generator_proto_rawDescOnce.Do(func() {
		file_mission_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_mission_generator_proto_rawDescData)
	})
	return file_mission_generator_proto_rawDescData
}

var file_mission_generator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mission_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mission_generator_proto_goTypes = []interface{}{
	(GenerateMissionRequest_MissionFormat)(0), // 0: mGenerator.GenerateMissionRequest.MissionFormat
	(*GenerateMissionRequest)(nil),            // 1: mGenerator.GenerateMissionRequest
	(*Point)(nil),                             // 2: mGenerator.Point
	(*Mission)(nil),                           // 3: mGenerator.Mission
	(*Mission_Twist)(nil),                     // 4: mGenerator.Mission.Twist
	(*Mission_Deployment)(nil),                // 5: mGenerator.Mission.Deployment
	(*Mission_Battlefield)(nil),               // 6: mGenerator.Mission.Battlefield
	(*Mission_Objective)(nil),                 // 7: mGenerator.Mission.Objective
	(*Mission_Terrain)(nil),                   // 8: mGenerator.Mission.Terrain
	(*Mission_Terrain_Category)(nil),          // 9: mGenerator.Mission.Terrain.Category
	(*Mission_Terrain_Trait)(nil),             // 10: mGenerator.Mission.Terrain.Trait
}
var file_mission_generator_proto_depIdxs = []int32{
	0,  // 0: mGenerator.GenerateMissionRequest.missionFormat:type_name -> mGenerator.GenerateMissionRequest.MissionFormat
	2,  // 1: mGenerator.Point.links:type_name -> mGenerator.Point
	4,  // 2: mGenerator.Mission.twist:type_name -> mGenerator.Mission.Twist
	5,  // 3: mGenerator.Mission.deployment:type_name -> mGenerator.Mission.Deployment
	6,  // 4: mGenerator.Mission.battlefield:type_name -> mGenerator.Mission.Battlefield
	7,  // 5: mGenerator.Mission.objectives:type_name -> mGenerator.Mission.Objective
	8,  // 6: mGenerator.Mission.terrain:type_name -> mGenerator.Mission.Terrain
	2,  // 7: mGenerator.Mission.Deployment.player_a_points:type_name -> mGenerator.Point
	2,  // 8: mGenerator.Mission.Deployment.player_b_points:type_name -> mGenerator.Point
	2,  // 9: mGenerator.Mission.Deployment.distance_points:type_name -> mGenerator.Point
	2,  // 10: mGenerator.Mission.Objective.objective_points:type_name -> mGenerator.Point
	9,  // 11: mGenerator.Mission.Terrain.category:type_name -> mGenerator.Mission.Terrain.Category
	10, // 12: mGenerator.Mission.Terrain.traits:type_name -> mGenerator.Mission.Terrain.Trait
	2,  // 13: mGenerator.Mission.Terrain.point:type_name -> mGenerator.Point
	1,  // 14: mGenerator.MissionGenerator.Generate:input_type -> mGenerator.GenerateMissionRequest
	3,  // 15: mGenerator.MissionGenerator.Generate:output_type -> mGenerator.Mission
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_mission_generator_proto_init() }
func file_mission_generator_proto_init() {
	if File_mission_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mission_generator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Twist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Battlefield); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Objective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Terrain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Terrain_Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Terrain_Trait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mission_generator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mission_generator_proto_goTypes,
		DependencyIndexes: file_mission_generator_proto_depIdxs,
		EnumInfos:         file_mission_generator_proto_enumTypes,
		MessageInfos:      file_mission_generator_proto_msgTypes,
	}.Build()
	File_mission_generator_proto = out.File
	file_mission_generator_proto_rawDesc = nil
	file_mission_generator_proto_goTypes = nil
	file_mission_generator_proto_depIdxs = nil
}
