// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.6.1
// source: mission_generator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MissionGeneratorClient is the client API for MissionGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MissionGeneratorClient interface {
	Generate(ctx context.Context, in *GenerateMissionRequest, opts ...grpc.CallOption) (*Mission, error)
}

type missionGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewMissionGeneratorClient(cc grpc.ClientConnInterface) MissionGeneratorClient {
	return &missionGeneratorClient{cc}
}

func (c *missionGeneratorClient) Generate(ctx context.Context, in *GenerateMissionRequest, opts ...grpc.CallOption) (*Mission, error) {
	out := new(Mission)
	err := c.cc.Invoke(ctx, "/mGenerator.MissionGenerator/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MissionGeneratorServer is the server API for MissionGenerator service.
// All implementations must embed UnimplementedMissionGeneratorServer
// for forward compatibility
type MissionGeneratorServer interface {
	Generate(context.Context, *GenerateMissionRequest) (*Mission, error)
	mustEmbedUnimplementedMissionGeneratorServer()
}

// UnimplementedMissionGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedMissionGeneratorServer struct {
}

func (UnimplementedMissionGeneratorServer) Generate(context.Context, *GenerateMissionRequest) (*Mission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedMissionGeneratorServer) mustEmbedUnimplementedMissionGeneratorServer() {}

// UnsafeMissionGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MissionGeneratorServer will
// result in compilation errors.
type UnsafeMissionGeneratorServer interface {
	mustEmbedUnimplementedMissionGeneratorServer()
}

func RegisterMissionGeneratorServer(s grpc.ServiceRegistrar, srv MissionGeneratorServer) {
	s.RegisterService(&MissionGenerator_ServiceDesc, srv)
}

func _MissionGenerator_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionGeneratorServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mGenerator.MissionGenerator/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionGeneratorServer).Generate(ctx, req.(*GenerateMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MissionGenerator_ServiceDesc is the grpc.ServiceDesc for MissionGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MissionGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mGenerator.MissionGenerator",
	HandlerType: (*MissionGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _MissionGenerator_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mission_generator.proto",
}
