<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator\GenerateMissionRequest;

/**
 * Protobuf type <code>mGenerator.GenerateMissionRequest.MissionFormat</code>
 */
class MissionFormat
{
    /**
     * Generated from protobuf enum <code>COMBAT_PATROL = 0;</code>
     */
    const COMBAT_PATROL = 0;
    /**
     * Generated from protobuf enum <code>INCURSION = 1;</code>
     */
    const INCURSION = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MissionFormat::class, \MGenerator\GenerateMissionRequest_MissionFormat::class);

