<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\GenerateMissionRequest\MissionFormat instead.
     * @deprecated
     */
    class GenerateMissionRequest_MissionFormat {}
}
class_exists(GenerateMissionRequest\MissionFormat::class);
@trigger_error('MGenerator\GenerateMissionRequest_MissionFormat is deprecated and will be removed in the next major release. Use MGenerator\GenerateMissionRequest\MissionFormat instead', E_USER_DEPRECATED);

