<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mGenerator.Mission</code>
 */
class Mission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     */
    private $rules = '';
    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Twist twist = 4;</code>
     */
    private $twist = null;
    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Deployment deployment = 5;</code>
     */
    private $deployment = null;
    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Battlefield battlefield = 6;</code>
     */
    private $battlefield = null;
    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Objective objectives = 7;</code>
     */
    private $objectives;
    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Terrain terrain = 8;</code>
     */
    private $terrain;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $description
     *     @type string $rules
     *     @type \MGenerator\Mission\Twist $twist
     *     @type \MGenerator\Mission\Deployment $deployment
     *     @type \MGenerator\Mission\Battlefield $battlefield
     *     @type \MGenerator\Mission\Objective[]|\Google\Protobuf\Internal\RepeatedField $objectives
     *     @type \MGenerator\Mission\Terrain[]|\Google\Protobuf\Internal\RepeatedField $terrain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MissionGenerator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     * @return string
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRules($var)
    {
        GPBUtil::checkString($var, True);
        $this->rules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Twist twist = 4;</code>
     * @return \MGenerator\Mission\Twist
     */
    public function getTwist()
    {
        return $this->twist;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Twist twist = 4;</code>
     * @param \MGenerator\Mission\Twist $var
     * @return $this
     */
    public function setTwist($var)
    {
        GPBUtil::checkMessage($var, \MGenerator\Mission_Twist::class);
        $this->twist = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Deployment deployment = 5;</code>
     * @return \MGenerator\Mission\Deployment
     */
    public function getDeployment()
    {
        return $this->deployment;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Deployment deployment = 5;</code>
     * @param \MGenerator\Mission\Deployment $var
     * @return $this
     */
    public function setDeployment($var)
    {
        GPBUtil::checkMessage($var, \MGenerator\Mission_Deployment::class);
        $this->deployment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Battlefield battlefield = 6;</code>
     * @return \MGenerator\Mission\Battlefield
     */
    public function getBattlefield()
    {
        return $this->battlefield;
    }

    /**
     * Generated from protobuf field <code>.mGenerator.Mission.Battlefield battlefield = 6;</code>
     * @param \MGenerator\Mission\Battlefield $var
     * @return $this
     */
    public function setBattlefield($var)
    {
        GPBUtil::checkMessage($var, \MGenerator\Mission_Battlefield::class);
        $this->battlefield = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Objective objectives = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectives()
    {
        return $this->objectives;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Objective objectives = 7;</code>
     * @param \MGenerator\Mission\Objective[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MGenerator\Mission\Objective::class);
        $this->objectives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Terrain terrain = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTerrain()
    {
        return $this->terrain;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Mission.Terrain terrain = 8;</code>
     * @param \MGenerator\Mission\Terrain[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTerrain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MGenerator\Mission\Terrain::class);
        $this->terrain = $arr;

        return $this;
    }

}

