<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator\Mission;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mGenerator.Mission.Deployment</code>
 */
class Deployment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_a_points = 1;</code>
     */
    private $player_a_points;
    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_b_points = 2;</code>
     */
    private $player_b_points;
    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point distance_points = 3;</code>
     */
    private $distance_points;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $player_a_points
     *     @type \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $player_b_points
     *     @type \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $distance_points
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MissionGenerator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_a_points = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayerAPoints()
    {
        return $this->player_a_points;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_a_points = 1;</code>
     * @param \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayerAPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MGenerator\Point::class);
        $this->player_a_points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_b_points = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayerBPoints()
    {
        return $this->player_b_points;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point player_b_points = 2;</code>
     * @param \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayerBPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MGenerator\Point::class);
        $this->player_b_points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point distance_points = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDistancePoints()
    {
        return $this->distance_points;
    }

    /**
     * Generated from protobuf field <code>repeated .mGenerator.Point distance_points = 3;</code>
     * @param \MGenerator\Point[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDistancePoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MGenerator\Point::class);
        $this->distance_points = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Deployment::class, \MGenerator\Mission_Deployment::class);

