<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator\Mission\Terrain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mGenerator.Mission.Terrain.Trait</code>
 */
class PBTrait extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string rules = 2;</code>
     */
    private $rules = '';
    /**
     * Generated from protobuf field <code>string rules_short = 3;</code>
     */
    private $rules_short = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $rules
     *     @type string $rules_short
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MissionGenerator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rules = 2;</code>
     * @return string
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>string rules = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRules($var)
    {
        GPBUtil::checkString($var, True);
        $this->rules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rules_short = 3;</code>
     * @return string
     */
    public function getRulesShort()
    {
        return $this->rules_short;
    }

    /**
     * Generated from protobuf field <code>string rules_short = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRulesShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->rules_short = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PBTrait::class, \MGenerator\Mission_Terrain_Trait::class);

