<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Objective instead.
     * @deprecated
     */
    class Mission_Objective {}
}
class_exists(Mission\Objective::class);
@trigger_error('MGenerator\Mission_Objective is deprecated and will be removed in the next major release. Use MGenerator\Mission\Objective instead', E_USER_DEPRECATED);

