<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Deployment instead.
     * @deprecated
     */
    class Mission_Deployment {}
}
class_exists(Mission\Deployment::class);
@trigger_error('MGenerator\Mission_Deployment is deprecated and will be removed in the next major release. Use MGenerator\Mission\Deployment instead', E_USER_DEPRECATED);

