<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Battlefield instead.
     * @deprecated
     */
    class Mission_Battlefield {}
}
class_exists(Mission\Battlefield::class);
@trigger_error('MGenerator\Mission_Battlefield is deprecated and will be removed in the next major release. Use MGenerator\Mission\Battlefield instead', E_USER_DEPRECATED);

