<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Terrain\Category instead.
     * @deprecated
     */
    class Mission_Terrain_Category {}
}
class_exists(Mission\Terrain\Category::class);
@trigger_error('MGenerator\Mission_Terrain_Category is deprecated and will be removed in the next major release. Use MGenerator\Mission\Terrain\Category instead', E_USER_DEPRECATED);

