<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Terrain instead.
     * @deprecated
     */
    class Mission_Terrain {}
}
class_exists(Mission\Terrain::class);
@trigger_error('MGenerator\Mission_Terrain is deprecated and will be removed in the next major release. Use MGenerator\Mission\Terrain instead', E_USER_DEPRECATED);

