<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator;

if (false) {
    /**
     * This class is deprecated. Use MGenerator\Mission\Terrain\PBTrait instead.
     * @deprecated
     */
    class Mission_Terrain_Trait {}
}
class_exists(Mission\Terrain\PBTrait::class);
@trigger_error('MGenerator\Mission_Terrain_Trait is deprecated and will be removed in the next major release. Use MGenerator\Mission\Terrain\PBTrait instead', E_USER_DEPRECATED);

