<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace MGenerator\Mission;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mGenerator.Mission.Battlefield</code>
 */
class Battlefield extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     */
    private $width = 0;
    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     */
    private $height = 0;
    /**
     * Generated from protobuf field <code>int32 power_level = 4;</code>
     */
    private $power_level = 0;
    /**
     * Generated from protobuf field <code>int32 points = 5;</code>
     */
    private $points = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type int $width
     *     @type int $height
     *     @type int $power_level
     *     @type int $points
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MissionGenerator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 power_level = 4;</code>
     * @return int
     */
    public function getPowerLevel()
    {
        return $this->power_level;
    }

    /**
     * Generated from protobuf field <code>int32 power_level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPowerLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->power_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 points = 5;</code>
     * @return int
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>int32 points = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPoints($var)
    {
        GPBUtil::checkInt32($var);
        $this->points = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Battlefield::class, \MGenerator\Mission_Battlefield::class);

